[package]
name = "phantom"
version = "0.1.0"
edition = "2021"

description = "A forward mode autodiff and deep learning library for Rust"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.75"
thiserror = "1"
