[package]
name = "phantom-core"
version = "0.1.0"
edition = "2021"

description = "A forward mode autodiff and deep learning library for Rust"
license = "MIT"
readme = "../../README.md"

[dependencies]
